baseURL = "http://uxd-lcc.org/"
footnoteReturnLinkContents = "â†©"
title = "BA (Hons) UXD at LCC, UAL"
theme = "uxdlcc"
publishDir = "docs"

[params]
  AuthorName = "UXD"
  GitHubUser = "http://github.com/uxd-lcc"
  thumbnail = "img/uxd_logo.png"

[permalinks]
  posts = "/:section/:title/"
